sudo: required

services:
  - docker

before_install:
  - docker build -t malves92/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true malves92/react-test npm test

after_success:
  - docker build -t malves92/multi-client ./client
  - docker build -t malves92/multi-nginx ./nginx
  - docker build -t malves92/multi-server ./server
  - docker build -t malves92/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push them to docker hub
  - docker push malves92/multi-client
  - docker push malves92/multi-nginx
  - docker push malves92/multi-server
  - docker push malves92/multi-worker

#deploy:
#   - ...